baseURL = "https://www.interus.com.ua/"
theme = "interus-theme"
defaultContentLanguage = "ua"

[params]
  email = "info@interus.com.ua"
  phone = "+38(044)337-64-03" 
  facebook = "https://www.facebook.com/interUs2017/"

  
# Languages
[languages.ua]
  languageName = "Укр"
 
  copyright = "2017-2018. ТОВ \"Інтерас\""  
  facebookLinkCaption = "Сторінка Facebook"
  footerCol1 = [
    "#### Про нас",
    "<p>Ми – команда однодумців, що люблять свою країну, “мріють про” та “працюють для” її процвітання",
    "[Детальніше...](/about/)"
  ]
  footerCol2 = [
    '#### Графік роботи',
    '<p>Будні: 9:00 — 18:00',
    '<p>Субота — Неділя: вихідний'
  ]
  footerCol3 = [
    '#### Наші контакти',
    '<p>04119',
    '<p>м. Київ',
    '<p>вул. Зоологічна 4а, оф. 139'
  ]
  
  

  [[languages.ua.menu.main]]
    url = "/"
    name = "Головна"
    weight = 1
  [[languages.ua.menu.main]]
    url = "/about/"
    name = "Про нас"
    weight = 2
  [[languages.ua.menu.main]]
    url = "/contact/"
    name = "Контакти"
    weight = 3

[languages.ru]
  languageName = "Рус"

  copyright = "2017-2018. ООО \"Интерас\""
  facebookLinkCaption = "Страница Facebook"

  footerCol1 = [
    "#### О нас",
    "<p>Мы – команда единомышленников, которые любят свою страну, “мечтают о” и “трудятся для” ее процветания",
    "[Подбробнее...](/ru/about/)"
  ]
  footerCol2 = [
    '#### График работы',
    '<p>Будние: 9:00 — 18:00',
    '<p>Суббота — Воскресенье: выходной'
  ]
  footerCol3 = [
    '#### Наши контакты',
    '<p>04119',
    '<p>м. Киев',
    '<p>вул. Зоологическая 4а, оф. 139'
  ]

  [[languages.ru.menu.main]]
    url = "/ru/"
    name = "Главная"
    weight = 1
  [[languages.ru.menu.main]]
    url = "/about/"
    name = "О нас"
    weight = 2
  [[languages.ru.menu.main]]
    url = "/contact/"
    name = "Контакты"
    weight = 3

[languages.en]
  languageName = "En"

  copyright = "2017-2018. \"Interus\" Ltd"
  facebookLinkCaption = "Facebook page"

  footerCol1 = [
    "#### About us",
    "<p>We are a team of like-minded people who love their country, \"settle about\" and \"work for\" its prosperity",
    "[Details...](/en/about/)"
  ]
  footerCol2 = [
    '#### Schedule',
    '<p>Weekdays: 9:00 - 18:00',
    '<p>Saturday - Sunday: closed'
  ]
  footerCol3 = [
    '#### Contacts',
    '<p>04119',
    '<p>Kyiv',
    '<p>Zoologichna Street, 4а, off. 139'
  ]

  [[languages.en.menu.main]]
    url = "/en/"
    name = "Main"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About us"
    weight = 2
  [[languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3

